
---
# tasks file for snmpd

- name: Instala serviço do snmp "{{ ansible_distribution }}" versão "{{ ansible_distribution_major_version }}"
  apt: 
    name: snmp 
    state: installed 
    update_cache: yes
  when: ( ansible_os_family == "Debian" )
  register: reusult
  notify:
    - Restart snmpd

- name: Instala serviço do snmp "{{ ansible_distribution }}" versão "{{ ansible_distribution_major_version }}"
  yum: 
    name: net-snmp 
    state: installed
  when: ( ansible_os_family == "RedHat" )
  register: result
  notify:
    - Start snmpd

- name: Define o arquivo de configuracao do servidor snmp  
  copy: 
    src: snmpd.conf 
    dest: /etc/snmp/snmpd.conf 
    owner: root 
    group: root 
    mode: 0640
  notify:
    - Restart snmpd
  when: result is success
...
