---
# handlers file for snmp
- name: Start snmpd
  service: name=snmpd state=started #enable=yes
  
- name: Stop snmpd
  service: name=snmpd state=stoped
  
- name: Restart snmpd
  service: name=snmpd state=restarted 

- name: Restart Windows SNMP Service
  win_service:
          name: SNMP
          state: restarted
...
